name       : gnugo
version    : 3.8
release    : 3
source     :
    - http://ftp.gnu.org/gnu/gnugo/gnugo-3.8.tar.gz : da68d7a65f44dcf6ce6e4e630b6f6dd9897249d34425920bfdd4e07ff1866a72
license    : GPL-3.0+
component  : games.strategy
summary    : GNU Go is a free program that plays the game of Go.
description: |
    GNU Go is a free program that plays the game of Go.
environment: |
    export CFLAGS="${CFLAGS} -fcommon" # gcc10
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
